### ISSUE TITLE
Note that the `CD` triggering mechanism is on `git tag`

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/ACCESS-OM2#33]
Pinging @harshula to remind him to push a tag to start the deployment process for `ACCESS-OM2`, when priority work is completed.

**Comment by harshula** [comment]
Thanks. Just want to confirm, you want me to do this only once you have completed your high priority tasks, in case something goes wrong with CD?

**Comment by CodeGat** [comment]
Correctamundo

**Comment by CodeGat** [comment]
No longer!
