### ISSUE TITLE
Consider Prereleases to use `MODEL-PR#-BUILD` rather than `MODEL-VERSION-BUILD`

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/ACCESS-OM2#56]
Currently, we use `MODEL-VERSION-BUILD` (for example, `access-om2-2024_03_0-2` where `MODEL=access-om2`, `VERSION=2024_03_0`, `BUILD=2`) to disambiguate our prerelease environments. 
During the skillshare, there was a suggestion that instead of `VERSION` we should use the PR number instead. This would allow a direct connection to a pull request (which is for now the only way we can prerelease). 
This could look something like `MODEL-PR#-BUILD` (`access-om2-pr2-1` or `access-om2-2-1`).

**Comment by aidanheerdegen** [comment]
This means a pre-release environment can be deployed without requiring a valid version.

That could de-couple the version logic from the PR and shift the version checks to something that is only required before merging.
