### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/ACCESS-OM2#79]
The readme refers to some spack instructions on access-hive which are out of date

I think the whole Build section could be shorted and point people to https://github.com/ACCESS-NRI/ACCESS-OM2/blob/main/DEVELOPERS.md

**Comment by harshula** [comment]
Hi @anton-seaice , Is this issue fixed by the commit on Sep 26, 2024 in https://github.com/ACCESS-NRI/ACCESS-OM2/commits/main/DEVELOPERS.md ?

**Comment by anton-seaice** [comment]
Looks good - thanks

**Comment by anton-seaice** [comment]
Closed through https://github.com/ACCESS-NRI/ACCESS-OM2/pull/80
