### ISSUE TITLE
Failed concretization of Spack environment

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/ACCESS-OM2#81]
## Description
While testing the future documentation for how to build a package with `spack develop`, I got into the following error when trying to concretize the ACCESS-OM2 environment (created from [this repo's spack.yaml](https://github.com/ACCESS-NRI/ACCESS-OM2/blob/main/spack.yaml)):
```
==> Error: concretization failed for the following reasons:

   1. No valid value for variant 'deterministic' of package 'access-om2'
```

## Steps to reproduce the error:
```
git clone https://github.com/ACCESS-NRI/ACCESS-OM2.git
spack env create myenv ACCESS-OM2/spack.yaml
spack env activate -p myenv
spack concretize -f
```

**Comment by harshula** [comment]
If you've made modifications to `spack.yaml`, you'll need to do `spack concretize -f --refresh`.

**Comment by harshula** [comment]
Otherwise, it's when the compiler isn't found.

**Comment by atteggiani** [comment]
I am only doing the steps listed in "Steps to reproduce the error:" above (after following the [spack setup](https://access-hive.org.au/getting_started/spack/)). 
If we put that in the instructions we have to make sure it will not generate the same error for the users.

**Comment by harshula** [comment]
Using `spack concretize -f --fresh` worked
